// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RootLayoutExtanded from "./rootLayout";
import LanguageRedirect from "@/components/languageRedirect";
import { AppProvider } from "../context/AppContext"; // Імпортуємо AppProvider
// import { Providers } from "./providers"; // Імпортуємо Providers
// import { SessionProvider } from "next-auth/react"; // Імпортуємо SessionProvider

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "EasyPlay",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full`}
      >
        <LanguageRedirect />
        <AppProvider>
          <RootLayoutExtanded>{children}</RootLayoutExtanded>
        </AppProvider>
      </body>
    </html>
  );
}
