import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import dynamic from "next/dynamic";
import "./globals.css";
import RootLayoutExtanded from "./rootLayout";
import LanguageRedirect from "@/components/languageRedirect";
// const LanguageRedirect = dynamic(
//   () => import("../components/languageRedirect"),
//   {
//     ssr: false,
//   }
// );

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "EasyPlay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full`}
      >
        <LanguageRedirect />
        <RootLayoutExtanded>{children}</RootLayoutExtanded>
      </body>
    </html>
  );
}
